# 处理例外

> [https://dev . to/stripes/manipulation-exceptions-4p11](https://dev.to/franiglesias/manejar-excepciones-4p11)

例外是语言中的元素，使我们能够指出中断程序正常流程的情况。当抛出异常时，该异常将提升语言调用堆栈，直到找到处理该异常的位置。如果找不到，程序流将停止并显示错误。

在某种程度上，我们可以将异常视为事件或消息发布，等待有兴趣的听众来处理。但是，它们不应用作应用程序的通用内部通信形式，而应仅用于特殊情况的管理。

以依赖远程 API 的应用程序为例。如果我们发现 API 在任何时候都不可用，这是一种特殊情况，最好是发出一个例外，说明这种特殊情况，这种情况无论如何都会使我们的程序无法运行。另一方面，我们的守则应等待是否发出这一具体例外，以便采取适当措施，或者警告用户不能进行这一操作，或者寻找某种替代办法等等。

语言则使用此机制来报告特定代码中可能出现的大部分一般错误。其中一些错误是逻辑错误，例如调用不存在的方法或传递无效类型的参数，而另一些错误则是*运行时错误，直到发生后才会被检测到，例如函数返回类型*

通常，可以通过分析代码来检测这些逻辑错误，并需要对代码进行修复以避免这些错误。就其本身而言，无法预测运行时错误，可能需要防御技术。

## [](#una-familia-excepcional)非同寻常的家庭

PHP 中的所有异常都来自基类`Exception`，而基类又实现接口`Throwable`(我们不能直接使用)。PHP 标准库(SPL)提供了包含两个主要分支的类树:

*   **logical exception**，它将表示程序逻辑错误的异常分组，进而扩展到:
    *   **badfunctioncalleexception**:调用不存在的函数或参数不正确时。
    *   **badmethod calleexception**:相同，但调用对象的方法时。
    *   **域异常**:一个值不在特定域特有的值范围内。例如，纬度 465 度。
    *   **无效参数异常**:传递给函数的参数类型不合适。
    *   **【lentheexception】**:某物的尺寸不合适。
    *   **OutOfRangeException** :请求非法索引，例如 70 项数组中的索引 100。
*   **RuntimeException** ，它将表示运行时检测到的错误的异常分组。在许多情况下，错误的含义与 logicexception 中的含义相同，但在运行时检测到错误时。
    *   **out of bounds exception**:Equivale a domain exception。
    *   **OverflowException** :表示向已满的容器添加元素的错误。
    *   **RangeException** :是`DomainException`的运行时版本。
    *   **UnderflowException** :典型的例子是试图从已经空的容器中取出一些东西。
    *   **UnexpectedValueException** :操作返回的值不是预期的类型。

当我们想在我们的法典中指出一个问题情况时，我们的任务是提出一个例外，尽管决定提出哪个具体的例外具有任意性。理想情况下，您可以选择刚才显示的其中一个例外，或者通过扩展最适合我们语义的类来创建自己的例外类型。

从许多方面来说，`LogicException`和`RuntimeException`的结构是平行的，在被解释为 PHP 的语言中是一种有点勉强的区分。在这两个分支之间进行权衡的标准是，我们是要强调必须对守则作出修改，以避免出现错误，还是强调问题是在执行过程中产生的，我们必须采取措施，处理我们无法预测是否会出现错误的情况。

## [](#la-excepci%C3%B3n-es-el-mensaje)例外是信息

最后，例外情况是一些消息，这些消息可能表明我们的代码有多种不利的情况，足以中断代码。

作为面向对象编程意义上的消息，异常必须提供语义值，因此，当自定义异常代表应用程序域中的重要情况时，最好定义自定义异常。

定义新的例外类型的一个很好的理由是，我们可以在方块`try…catch`中具体捕捉它们，就像我们稍后会看到的那样，使我们能够针对不同类型的问题采取适当的行动。

无论如何，重要的是例外尽可能地描述问题。

另一方面，`Exception`类构造函数允许我们定义:

*   描述所发生事件的信息，通常作为最终用户信息显示，我认为不应用于获取有关所发生问题的信息。
*   一个数字错误代码，它允许我们对异常所描述的问题进行细微调整。
*   以上例外，以防我们重新启动例外。

## [](#falla-espec%C3%ADficamente-y-captura-gen%C3%A9ricamente)具体故障，一般捕获

### [](#fallar-lanzando-excepciones)抛出异常失败

当我们的代码中有一部分必须处理潜在问题时，您可以检测到指出该问题的条件，并在满足这些条件时抛出异常。

例如，如果我们正在处理坐标，而我们收到的其中一个值在-180 ... 180 范围之外，则我们会有一个“T0”(或“`OutOfBoundsException`”的情况，因此任何后续操作都是毫无意义的。例如，我们可以做一个保留条款来检测它并引发异常:

```
if (abs($longitude) > 180) {
    throw new OutOfBoundsException('Bad value for Longitude');
} 
```

### [](#fallar-espec%C3%ADficamente)具体失败

我认为，理想的做法是以最具描述性和最准确的方式失败，这样，如果我们愿意的话，我们就可以对特定类型的错误采取行动，如果有特定的捕获块用于此类异常，就可以做到这一点。

这可能需要使用定制的例外，这些例外源自其他标准，或者至少是基本例外。但这基本上取决于我们的需要。

例如，假设您的应用程序需要对地理位置数据进行大量控制。在这种情况下，可能有如下例外:

```
class InvalidCoordinatesException extends OutOfBoundsException; 
```

这样你就可以做这样的事情:

```
if (abs($longitude) > 180) {
    throw new InvalidCoordinatesException('Out of range value of '.$longitude.' deg');
} 
```

### [](#capturar)Capturar

为了防止异常能够到达用户并中断我们的应用程序，我们需要某种类型的异常处理，为此我们有块`try…catch`。

`try…catch`块将*【快乐路径】*(如果没有问题的话程序流)与处理问题情况分开。最基本的例子如下:

```
try {
    // This is the happy path
} catch (Exception $exception) {
    // Catches all exceptions
    // Do something with $exception
    // Hey, at least log it
} 
```

如果在块`try`运行期间发生异常，则流停止并跳转到块`catch`。这个区块会被当做参数传递，在适当的情况下，您可以从中撷取资讯，并执行适当的动作，例如在错误记录中新增项目*，重新导向至特定页面，甚至重新掷回相同或不同的例外，让下一个应用程式层级*

 *此结构之后的代码仅在没有异常(即使已捕获)的情况下运行。

我们可以通过简单地添加块`catch`来捕获特定异常，但我们必须这样做，以便捕获较具体的异常，而不是较一般性的异常。

```
try {
    // This is the happy path
} catch (InvalidArgumentException $exception) {
    // Do something with this exception
} catch (Exception $exception) {
    // Catches all other exceptions
    // Do something with this exception
} 
```

如果我们需要一个代码始终运行，无论是否有异常，我们都会将其包含在块`finally`中。这使我们能够执行关闭文件、记录信息或使系统保持最佳状态所需的任何其他操作。

```
try {
    // This is the happy path
} catch (Exception $exception) {
    // Catches all exceptions
    // Do something with this exception
} finally {
    // This is executed always, even after a exception
    // or even after an exception was re-thrown
} 
```

### [](#capturar-gen%C3%A9ricamente)船长

此外，我认为，最好的策略是，即使我们有非常具体的例外情况，也要以尽可能广泛的方式开始捕捉:

```
try {
    // This is the happy path
} catch (Exception $exception) {
    // Catches all exceptions
} 
```

如果需要以特殊方式处理某一特定类型的异常，我们只需添加一个新的更具体的块`catch`。

```
try {
    // This is the happy path
} catch (InvalidCoordinatesException $exception) {
    // Do something with this exception
} catch (Exception $exception) {
    // Catches all other exceptions
    // Do something with this exception
} 
```

仅使用一般例外的问题是，如果我们在某个时候需要根据所发现的问题采取不同的行动，则例外很可能无法向我们提供足够的信息。

如果例外本身已经告诉我们发生了什么，就其类型而言，我们只需浏览其中的一些数据，就可以采取适当的行动。

并且**决不，决不**，我们应该有`catch`块什么都不做，沉默异常。至少，如果我们感兴趣的是不中断程序流，我们应该在*日志*中创建一个条目，以防检测到任何问题，这样可以在以后的分析中为我们提供一些线索。

## [](#relanzar-excepciones)重新引发异常

有时，您可能需要捕获一个异常才能重新抛出。当例外跨越应用程式图层之间的边界时，这个选项特别有用。

例如，我们可能在基础架构层中有一个数据库适配器，它在给定时间抛出异常，因为它无法连接到服务器。

如果此异常到达使用此适配器实施的存储库，则最好重新启动与存储库层匹配的新异常，例如:

```
// Repository.php

try {
    // Save data
} catch(MySQLConnectionException $exception) {
    throw new PersistenceException('Data could not be stored', 100, $exception);
} 
```

在此示例中，存储库处理来自数据库适配器的异常，但必须引发对域层有意义的异常。在这方面，该领域可能有兴趣了解持久性方面的问题，但不必了解持久性的具体实施情况。

异常支持第三个参数，用于包括以前捕获的异常，以便可以使用其信息。

## [](#excepciones-expresivas)表达例外

### [](#mant%C3%A9n-los-tipos-de-excepciones-bajo-control)保持异常类型的控制

创造新的例外情况，以便更好地描述所发生的错误，是一种良好做法，但也不应增加例外情况的数量。一般来说，必须提出例外情况，说明一类问题。

与其他概念一样，它的设计确实应该由消费者驱动。如果从发生问题的代码的角度来看，我们可能倾向于对每种类型的错误都要求例外。

例如，如果您正在设计一个与地理位置相关的应用程序，则坐标将是重要的概念，因此有一个名为“`InvalidCoordinatesException`”的例外情况说明了试图用无效值定义一对坐标的各种情况。

但是，有诸如`InvalidLongitudeException`或`InvalidLatitudeException`等例外情况是很值得商榷的，因为它们会过多地占用命名空间，而另一方面，在谈到**对**坐标时却没有多大意义。

### [](#payload-de-excepciones)异常有效负载

如果要创建自定义异常，建议这些异常可以包含有关错误情况的额外信息，然后可以使用简单的“*getter*”提取这些信息。就像这样：

```
class InvalidCoordinatesException extends InvalidArgumentException
{
    private $longitude;
    private $latitude;

    public function __construct($longitude, $latitude)
    {
        $this->longitude = $longitude;
        $this->latitude = $latitude;

        parent::__construct(sprintf('Coordinates (%s, %s) are invalid.', $longitude, $latitude));
    }

    public function getLatitude()
    {
        return $this->latitude;
    }

    public function getLongitude()
    {
        return $this->longitude;
    }
} 
```

虽然严格地说违反了 Liskov 的替换原则，但必须注意的是，例外将被捕获到一个块中，该块专门等待这种特定类型的例外，方法是使用 *type hinting* 。

### [](#named-constructors-en-excepciones)命名构造函数

一种可以提高异常表达性的技术是采用因子法(*命名构造函数*，这样这些新异常的构造不仅更具表达性，甚至更加一致。上述范例可改写如下:

```
class InvalidCoordinatesException extends \InvalidArgumentException
{
    private $longitude;
    private $latitude;

    private function __construct($longitude, $latitude)
    {
        $this->longitude = $longitude;
        $this->latitude = $latitude;

        parent::__construct(sprintf('Coordinates (%s, %s) are invalid.', $longitude, $latitude));
    }

    public static function for($longitude, $latitude) : self
    {
        return new static($longitude, $latitude);
    }

    public function getLatitude()
    {
        return $this->latitude;
    }

    public function getLongitude()
    {
        return $this->longitude;
    }
} 
```

所以我们可以像这样使用它(不要告诉我它不是一个美人):

```
throw InvalidCoordinatesException::for(229, 123); 
```*